/**
 * Isla AI mark.
 *
 * One island inside a ring of open water: the data stays on the island, the
 * water is the boundary it never crosses. Inlined as SVG rather than loaded as
 * a file so it inherits `currentColor`, needs no network request, and stays
 * crisp at any size - which is the point of a `default-src 'none'` app.
 *
 * Geometry is GENERATED by scripts/process_isla_logo.py into
 * branding/isla-mark.svg, and copied here verbatim. The inline copy is
 * deliberate - `currentColor` cannot cross an <img> boundary - so
 * isla-mark.test.tsx asserts this `d` still matches the generated SVG. If you
 * change one, change ISLAND_CURVES in the script and re-run it.
 *
 * branding/isla-ai-logo.png is the engraved master. It is not usable here: its
 * hatch is ~1px at 2813px wide, so anything under ~500px moires into grey mush.
 */
export function IslaMark({
  size = 26,
  className,
}: {
  size?: number;
  className?: string;
}) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 512 512"
      fill="none"
      role="img"
      aria-label="Isla AI mark"
      className={className}
    >
      <circle cx="256" cy="256" r="194" stroke="currentColor" strokeWidth="48" />
      <path
        fill="currentColor"
        d="M119.2 289.1 C132.2 266.8 153.8 241.9 175.4 222.1 C194.1 204.7 220.0 190.6 239.4 186.4 C264.6 181.5 288.4 194.7 309.3 214.6 C330.2 234.5 352.5 258.5 376.2 275.0 C384.2 280.0 389.9 284.2 388.5 290.8 C381.3 306.5 352.5 316.4 316.5 320.6 C273.3 325.6 215.7 320.6 172.5 309.8 C148.0 304.0 122.1 299.1 119.2 289.1 Z"
      />
    </svg>
  );
}

export default IslaMark;
